CFLAGS = -Wall -std=gnu99

tcp: tcp-server tcp-client

tcp-client: tcp-client.c errors.h messages.h

tcp-server: tcp-server.c errors.h messages.h

uds: uds-client uds-server

uds-client: uds-client.c errors.h

uds-server: uds-server.c errors.h
